AllCops:
  NewCops: enable
  Exclude:
    - "db/**/*"
    - "tmp/**/*"
    - "log/**/*"

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ArrayAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineEndStringConcatenationIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/SpaceBeforeBrackets:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

Metrics/BlockLength:
  Exclude:
    - "spec/rails_helper.rb"
    - "spec/**/*_spec.rb"
    - "spec/factories/**/*.rb"
    - "config/routes.rb"

Metrics/MethodLength:
  CountAsOne:
    - array
    - hash
    - heredoc

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/CommandLiteral:
  EnforcedStyle: percent_x

Style/DoubleNegation:
  Enabled: false

Style/RescueStandardError:
  EnforcedStyle: implicit

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/RaiseArgs:
  EnforcedStyle: compact

Style/RegexpLiteral:
  EnforcedStyle: percent_r
