Rails/ActionOrder:
  ExpectedOrder:
    - index
    - show
    - new
    - create
    - edit
    - update
    - destroy

Rails/ThreeStateBooleanColumn:
  Enabled: false
  
Rails/WhereExists:
  EnforcedStyle: where
